### ISSUE TITLE
Error on a dynamic route

### ISSUE THREAD

**Issue by edkahara** [i18next/next-language-detector#1]
I'm getting an error when implementing your solution on a dynamic route. In my case I'm trying to show a blog post on `/blog/[id]` that is fetched using `getServerSideProps`, but I get the following error. On the console it says 
```
compiling /[locale]/blog/[id]...
thread '<unnamed>' panicked at 'You can not use getStaticProps or getStaticPaths with getServerSideProps. To use SSG, please remove getServerSideProps'

Error: A required parameter (id) was not provided as a string in getStaticPaths for /[locale]/blog/[id]
```
 Is there a solution for this? Could you include an example of this?
<img width="965" alt="Screenshot 2021-12-13 at 17 59 24" src="https://user-images.githubusercontent.com/20911240/145835573-d49afafa-41c8-43eb-b5bf-4f534927a9ee.png">

**Comment by adrai** [comment]
You need to do what is written in your error message.

Example here slug instead of id: https://github.com/adrai/next-static-i18n-test/blob/fe811e6a5fc4ff8453ac94dbb133a244f59b9e8b/pages/%5Blocale%5D/blog/%5Bslug%5D.js#L26
