### ISSUE TITLE
Abort fetching component for route: "/[locale]" error when i transfrom to typescript 

### ISSUE THREAD

**Issue by frontendcz** [i18next/next-language-detector#4]
## To Reproduce

A [minimal reproducible example](https://minimum-reproduction.wtf/).
A [codesandbox](https://codesandbox.io/examples/package/i18next) example or similar
or at least steps to reproduce the behavior:

```js
// Paste your code here
```

## Expected behavior

```js
// Paste the expected results here
```

## Your Environment

- *runtime version*: i.e. node v14, deno, browser xy
- *i18next version*: i.e. 19.5.3
- *os*: Mac, Windows, Linux
- *any other relevant information*

**Comment by adrai** [comment]
Sorry, I don't know what you mean.
