### ISSUE TITLE
Use reloadOnPrerender to update changed language files

### ISSUE THREAD

**Issue by achimmihca** [i18next/next-language-detector#5]
## 🐛 Bug Report

It is not really a bug, only a small issue I have with [examples/basic](https://github.com/i18next/next-language-detector/tree/main/examples/basic): Changed language files are not updated in developer mode without restarting node.

To solve this, the i18next-config option `reloadOnPrerender: true` can be set in [next-i18next.config.js](https://github.com/i18next/next-language-detector/blob/main/examples/basic/next-i18next.config.js).
See the Pull Request for details: https://github.com/i18next/next-i18next/pull/1359

### To Reproduce

- Run examples/basic
- Change translation file and reload page.
- -> Changed translation is not visible

### Expected behavior

Add `reloadOnPrerender` to next-i18next.config.js.

- Run examples/basic
- Change translation file and reload page.
- -> Changed translation is used as expected

## Besides this
I also suggest to specify `localeExtension: 'yml'` (https://github.com/i18next/next-i18next/pull/302) in next-i18next.config.js and use yml files instead of JSON to get rid of the noisy JSON syntax (no curly braces, quotes and commas).

## Thanks
Thank you for this great example on how to set up localization in SSG! It has helped me a lot.
I only think it would be even better with yml files and `reloadOnPrerender`.

**Comment by adrai** [comment]
added reloadOnPrerender, but will keep json as it is the default and I personally like it more.
